### ISSUE TITLE
Unable to acces Token

### ISSUE THREAD

**Issue by JohnTheBeloved** [antony/grails-oauth-scribe#44]
I have tried all I can but still receiving this error then I log the exception thrown in the OAuthController

{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}'

Found out the Authentication header is not being by plugin set when sending the request to my Provider

please what is wrong?

**Comment by antony** [comment]
What provider are you trying to authenticate with?

**Comment by JohnTheBeloved** [comment]
Very sorry for the late response,

Summarising, I have two issues

 1. No authentication Header in Token Request(2nd call)
 2. Token authentication does not match TOKEN_REGEX

The provider I am implementing for is a private Oauth Implementation using Spring, the first authentication("oauth/authorize") call is OK which redirects the users to the login screen of the provider after login in, I receive the code, the callback url is also called but due to no **Authentication Header** I received a '{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}'' response

I had to manually hack the grails plugin to sign the header with this snippet

    public class OAuth20ServiceImpl implements OAuthService
    {
     
          ...methods

         public Token getAccessToken((Token requestToken, Verifier verifier)
         {
         
              ...statements
           
              request.addHeader(OAuthConstants.HEADER, "Basic c21hcnRpbnN1cmU6c2VjcmV0");
           
              ...statements

          }

            ...othermethods

      }

This hack made me get this response below
     `{"access_token":"eyJhbGciOiJSUzI1NiJ9.eyJhdWQiOlsicGFzc3BvcnQiXSwiZXhwIjoxNDI2NjYwNDYzLCJ1c2VyX25hbWUiOiJqb2huLmFsYWRlIiwianRpIjoiMDk3Y2VlYmItNTQ1Zi00MDI0LWI3OGQtMzEzZGViYjJjY2IxIiwiY2xpZW50X2lkIjoic21hcnRpbnN1cmUiLCJzY29wZSI6WyJwcm9maWxlIl19.M4Vzpi_iR4OVqV1tolw9Fn_KchjWuyY4l1yv4rwEl4BB_kXFgXQt8ccqP-oxLE7tE-QfQu6u-Dmb7rez_3umVE8PphHsG0ysvR-XKSFyLqrKDZHKHQ2Q-VnpPzJ4QUuS1tmmQKjtD2fKg8hG7wmJDyZqpM3cG_BosAAM6IRuyx5h3dRBqDjOX8_WOubeSEWtsjCD11EjurUQDly9NaVu7cUBJYn-b03FN3BJqVSWejBn_RCweB31fsrp8TJPiHfXsfoHedpb9LntNtH1eh3vnjM2zt8Kis1Mx3cTDkfWV7FdmKHaYSm4N3bT3PCY-QPWbCV2_NI2dMQBpLMzj29pNg","token_type":"bearer","refresh_token":"eyJhbGciOiJSUzI1NiJ9.eyJhdWQiOlsicGFzc3BvcnQiXSwidXNlcl9uYW1lIjoiam9obi5hbGFkZSIsInNjb3BlIjpbInByb2ZpbGUiXSwiYXRpIjoiMDk3Y2VlYmItNTQ1Zi00MDI0LWI3OGQtMzEzZGViYjJjY2IxIiwiZXhwIjoxNDI5MjA5MjYzLCJqdGkiOiJkZmFjNzY4OS03ZGNhLTRhYjEtYWMwMS01MjEwNmY5ODBlNTMiLCJjbGllbnRfaWQiOiJzbWFydGluc3VyZSJ9.gSThfduy55LMN-uIDVE-fr4uqxIf2Sq-mnYVyxKwUdYyCjKBRJwn_ZrYsPVjvI1MTpsBnWQ_-MTrQdDmpz4f0dyv4WkLSv3avQ-ASi4j89AVFwLhC68oLlYURbIJ3j8MZfPyv5Lz-_YZG-SmHdzAYQHBlAeT2OXD5OybYJbJz0_7ODJaSYzJlGtsl3BZ-DGtbyHUn9TPkxGbqzv_RmvHzbm5u7PDYUfrpZwYaj7PM66YrCXYgbQWY79KvlqhAAFlWMW71mvhmnnNhSEj7Dw3Q2eUTNtKyUqgAvPv7a3WnIAz6taz2yk4QVPtcg0JQWFJPdwPQsgRuV-ZMINAiLSY8Q","expires_in":43199,"scope":"profile","jti":"097ceebb-545f-4024-b78d-313debb2ccb1"}`

However, the access token is a JWT base64 encoded token which did not match this pattern(  `private static final String TOKEN_REGEX = "access_token=([^&]+)";`) in **TokenExtractor20Impl** class, I had to hack the class also to implement my own token(
  `private static final String PASSPORT_TOKEN_REGEX = "access_token([^,]*)");`

This hack should be temporary, Please how can I do this normarly as I want to implement this before commiting, Thanks

**Comment by antony** [comment]
Hi @JohnTheBeloved 

This sounds like a symptom of the Oauth 2.0 spec. Basically people implement it however they like, and there are no real standards.

What your provider is doing is completely custom and is only relevant to their particular 2.0 implementation. This means to implement it in a generic plugin isn't really possible.

The oauth-grails plugin relies on the scribe java library which, for this exact reason, is largely dropping Oauth 2.0 support. This makes it even more difficult to support since I rely on this library.

Unfortunately this means that with Oauth 2.0 you are kinda on your own. You could:

- Fork and adapt the plugin to meet your needs
- Use a library provided by your provider
- Just build your own oauth support - this is what the scribe author suggests.

Sorry I can't be of more help here!

For more info on this, see here: https://github.com/fernandezpablo85/scribe-java/wiki/Scribe-scope-revised

**Comment by JohnTheBeloved** [comment]
Thanks a lot @antony , I have forked the project and customized it to meet the spec.....I honestly appreciate your help

**Comment by antony** [comment]
A pleasure to help!
