### ISSUE TITLE
Can't auth with google

### ISSUE THREAD

**Issue by stefankendall** [antony/grails-oauth-scribe#45]
https://stackoverflow.com/questions/29830471/oauth-2-google-authentication-in-grails

I created this provider, but I get redirected to the failure Uri despite nothing obviously going wrong. How do I get this plugin authenticating with google?

    public class GoogleApi20 extends DefaultApi20 {
    private static final String AUTHORIZATION_URL =
            "https://accounts.google.com/o/oauth2/auth?client_id=%s&redirect_uri=%s&scope=%s&response_type=code";

    @Override
    public String getAuthorizationUrl(OAuthConfig config) {
        return String.format(AUTHORIZATION_URL, config.getApiKey(), config.getCallback(), config.getScope());
    }

    @Override
    public String getAccessTokenEndpoint() {
        return "https://accounts.google.com/o/oauth2/token";
    }

    @Override
    public Verb getAccessTokenVerb() {
        return Verb.POST;
    }

    @Override
    public AccessTokenExtractor getAccessTokenExtractor() {
        return new JsonTokenExtractor();
    }
    }

**Comment by antony** [comment]
Seems like your problem was fixed by https://gist.github.com/yincrash/2465453

Sorry I didn't notice this issue earlier (i.e. in April!) - not sure what happened!
