### ISSUE TITLE
Documentation link on grails.org plugin page is broken. Also add doc link in readme as well.

### ISSUE THREAD

**Issue by ejaz-ahmed** [antony/grails-oauth-scribe#47]

**Comment by antony** [comment]
How is it broken? Seems to work for me...

**Comment by ejaz-ahmed** [comment]
Grails plugin page points to https://aiten.github.com/grails-oauth-scribe/ which results inn 404. README file (not README.md) also points to this link which is broken. I am however able to access github.io page.

**Comment by antony** [comment]
I looked at the plugin page and it seems to point to antony.github.com which is correct? Which plugin page are you looking at?

I've deleted the readme. There is no sense in two readmes!

**Comment by antony** [comment]
Ah, spotted it. I'll fix.
