### ISSUE TITLE
Support for OAuth2

### ISSUE THREAD

**Issue by Omnipresent** [antony/grails-oauth-scribe#55]
This piece of code suggests that no token is prepare when the version of OAuth is 2

https://github.com/antony/grails-oauth-scribe/blob/master/grails-app/controllers/uk/co/desirableobjects/oauth/scribe/OauthController.groovy#L77

However, it seems that the plugin does support OAuth2?

Am I missing something?

**Comment by antony** [comment]
Hi,

The plugin supports OAuth2 by virtue of [Scribe Java](https://github.com/scribejava/scribejava) supporting OAuth 2.

**Comment by antony** [comment]
This will likely be addressed by #58

**Comment by antony** [comment]
v4.0.0 should solve your problem.
